import assert from 'node:assert/strict';
import worker from './groq-egress-worker.js';
const wav=new Uint8Array(44);wav.set(Buffer.from('RIFF'));wav.set(Buffer.from('WAVE'),8);
const req=(auth='Bearer test-key',body=wav,path='/transcribe')=>new Request('https://test.workers.dev'+path,{method:'POST',headers:{authorization:auth,'content-type':'audio/wav','content-length':String(body.length)},body});
const env={GROQ_KEY:'test-key'};
assert.equal((await worker.fetch(req('Bearer wrong'),env)).status,401);
assert.equal((await worker.fetch(req('Bearer test-key',wav,'/other'),env)).status,404);
assert.equal((await worker.fetch(req('Bearer test-key',new Uint8Array(3)),env)).status,413);
globalThis.fetch=async(url,opts)=>{assert.equal(url,'https://api.groq.com/openai/v1/audio/transcriptions');assert.equal(opts.body.get('model'),'whisper-large-v3');return new Response('{"text":"spoken"}');};
assert.equal((await (await worker.fetch(req(),env)).json()).text,'spoken');
globalThis.fetch=async()=>new Response('no',{status:403});assert.equal((await worker.fetch(req(),env)).status,503);
globalThis.fetch=async()=>new Response('{"text":null}');assert.equal((await worker.fetch(req(),env)).status,503);
globalThis.fetch=async()=>new Response('x'.repeat(65537));assert.equal((await worker.fetch(req(),env)).status,503);
globalThis.fetch=async()=>new Response('{bad json');assert.equal((await worker.fetch(req(),env)).status,503);
globalThis.fetch=async()=>new Response('no',{status:429});assert.equal((await worker.fetch(req(),env)).status,429);
globalThis.fetch=async()=>{throw new Error('timeout');};assert.equal((await worker.fetch(req(),env)).status,503);
assert.equal((await worker.fetch(req('Bearer test-key',new Uint8Array(44)),env)).status,400);
assert.equal((await worker.fetch(new Request('https://test.workers.dev/transcribe'),env)).status,404);
console.log('12 worker guards passed');
